FROM dockerhub.iis.sinica.edu.tw/huagi-8k

MAINTAINER sih4sing5hong5

COPY decode_nnet3.sh .

#COPY 走評估nnet3.sh ./val_nnet3.sh
#RUN bash -x val_nnet3.sh dd data/train

#COPY 4.wav /
#COPY kauthie.wav /4.wav
#COPY data data
#RUN bash -x decode_nnet3.sh exp/chain/tdnn_1a_sp/graph_test rescore data/train exp/chain/tdnn_1a_sp/decode_tshi

